# ── Run Configuration ───
qgis_apps: C:/Program Files/QGIS 3.34.10/apps/qgis

# coordinate reference system (CRS) for the project
crs: EPSG:32754

# ── Run Configuration ───
companies_run:
  - GPA
  - MNM

# Notification Configuration
parent_dir  : D:/00. Geo-AI Apps/automation of gap and weed detection/lib/pyqgis/
logo        : D:/00. Geo-AI Apps/automation of gap and weed detection/lib/pyqgis/input/logo/comp_logo.jpg
north_arrow : D:/00. Geo-AI Apps/automation of gap and weed detection/lib/pyqgis/input/svg/NorthArrow_11.svg

# ── Companies-specific configuration ───
companies:
  GPA:
    map_path            : D:/00. Geo-AI Apps/automation of gap and weed detection/maps/GPA/
    gdb_path            : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/GPA.gdb
    sugarcane_gdb_path  : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/Sugarcane-Raw_GPA_PT.gpkg
    gpkg_gaps_path      : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/Gaps-Detection_GPA_AR.gpkg
    map_index_extent    : 
      - 436555.000 # xmin
      - 9076954.533 # ymin
      - 481394.500 # xmax
      - 9100938.451 # ymax
  MNM:
    map_path            : D:/00. Geo-AI Apps/automation of gap and weed detection/maps/MNM/
    gdb_path            : D:/00. Geo-AI Apps/automation of gap and weed detection/database/MNM/MNM.gdb
    sugarcane_gdb_path  : D:/00. Geo-AI Apps/automation of gap and weed detection/database/MNM/Sugarcane-Raw_MNM_PT.gpkg
    gpkg_gaps_path      : D:/00. Geo-AI Apps/automation of gap and weed detection/database/MNM/Gaps-Detection_MNM_AR.gpkg
    map_index_extent    : 
      - 444063.005 # xmin
      - 9119777.967 # ymin
      - 488902.505 # xmax
      - 9143761.885 # ymax