# ── Run Configuration ───
qgis_apps: C:/Program Files/QGIS 3.34.10/apps/qgis

# coordinate reference system (CRS) for the project
crs: EPSG:32754

# ── Run Configuration ───
companies_run:
  - GPA
  # - MNM

# ── Companies Alias ───
companies_alias:
  c1: "GPA"
  c2: "MNM"

# Notification Configuration
logo          : D:/00. Geo-AI Apps/automation of gap and weed detection/lib/pyqgis/input/logo/comp_logo.jpg
north_arrow   : D:/00. Geo-AI Apps/automation of gap and weed detection/lib/pyqgis/input/svg/NorthArrow_11.svg
dam_gpa_path  : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/infra/DAM.shp
bin_dir       : D:/00. Geo-AI Apps/automation of gap and weed detection/bin/

# ── Companies-specific configuration ───
companies:
  GPA:
    map_title           : 'PT. GLOBAL PAPUA ABADI'
    map_path            : D:/automation of gap and weed detection/maps/GPA/
    landuse_path        : D:/automation of gap and weed detection/database/GPA/60_landuse.gdb
    sugarcane_gdb_path  : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/Sugarcane-Raw_GPA_PT.gpkg
    gpkg_gaps_path      : D:/00. Geo-AI Apps/automation of gap and weed detection/database/GPA/Gaps-Detection_GPA_AR.gpkg
    gpkg_gaps_planting_path : D:/automation of gap and weed detection/database/GPA/Gaps-Detection_GPA_Planting_AR.gpkg
    infra_path              : D:/automation of gap and weed detection/database/GPA/50_infrastructure.gdb
    planting_path           : D:/automation of gap and weed detection/database/GPA/20_planting.gdb
    water_body_path         : D:/automation of gap and weed detection/database/GPA/gpa_wb.gpkg
    map_index_extent    : 
      - 436555.000 # xmin
      - 9076954.533 # ymin
      - 481394.500 # xmax
      - 9100938.451 # ymax
  MNM:
    map_title           : 'PT. MURNI NUSANTARA MANDIRI'
    map_path            : D:/automation of gap and weed detection/maps/MNM/
    gdb_path            : D:/automation of gap and weed detection/database/MNM/MNM.gdb
    sugarcane_gdb_path  : D:/00. Geo-AI Apps/automation of gap and weed detection/database/MNM/Sugarcane-Raw_MNM_PT.gpkg
    gpkg_gaps_path      : D:/00. Geo-AI Apps/automation of gap and weed detection/database/MNM/Gaps-Detection_MNM_AR.gpkg
    gpkg_gaps_planting_path : D:/automation of gap and weed detection/database/MNM/Gaps-Detection_MNM_Planting_AR.gpkg
    soil_rehabilitation_path: D:/automation of gap and weed detection/database/MNM/soil_rehabilitation.gpkg
    land_status_path: D:/automation of gap and weed detection/database/MNM/land_status.gpkg
    land_status_v2_path: D:/automation of gap and weed detection/database/MNM/planting_land-status.parquet
    activity_summary_path: D:/automation of gap and weed detection/table/MNM_Activity_Summary_by_Paddock_flat_Planting Status.xlsx
    ripper_activity_path: D:/automation of gap and weed detection/database/MNM/activities/Ripper.parquet
    soil_ameliorant_activity_path: D:/automation of gap and weed detection/database/MNM/activities/Soil Ameliorant.parquet
    harrow_activity_path: D:/automation of gap and weed detection/database/MNM/activities/Harrow.parquet
    grubber_activity_path: D:/automation of gap and weed detection/database/MNM/activities/Grubber.parquet
    basal_activity_path: D:/automation of gap and weed detection/database/MNM/activities/Basal.parquet
    planting_path: D:/MSG/MNM_QGIS Project_packaged/mnm_planting.parquet
    map_index_extent    :
      - 444063.005 # xmin
      - 9119777.967 # ymin
      - 488902.505 # xmax
      - 9143761.885 # ymax